### ISSUE TITLE
Not an issue but a question about sharing a new plugin

### ISSUE THREAD

**Issue by alberti42** [ohmyzsh/wiki#64]
I did not find a discussion section. So I post my question here hoping to receive a short answer.

I made a plugin for syncing ssh remote sessions with the window names of local tmux: see my GitHub [page](https://github.com/alberti42/tmux-ssh-syncing)

The plugin works seamlessly with `oh-my-zsh`. Is there a way to advertise the plugin on a page of the oh-my-zsh framework? I had rather preferred to keep the plugin on my repository. Is it possible to post the plugin to oh-my-zsh repository as a submodule?

If I make a hard copy to oh-mh-zsh repository, how can I fix in the future bugs if I do not have the permission to make accept pull requests on my onw plugin?

I searched on the internet, but I could not find a clear answer to these questions. I hope to receive some clarification. Thanks!

**Comment by carlosala** [comment]
Indeed! You can open a PR as an `External Plugin` in this repo. If the plugin gets traction we could upstream it to the main ohmyzsh repo.
Thanks for the contribution!

**Comment by alberti42** [comment]
Thanks a lot for the reply! I made a pull request where I added tmux-ssh-syncing plugin to the external plugin page.
